import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Raleway_Dots } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ['latin']
})

const ralewayDots = Raleway_Dots({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-raleway-dots",
});

export const metadata: Metadata = {
  title: "Anay Paraswani",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figTree.variable} ${ralewayDots.variable} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
